sonar.projectKey=Agustin-Perezz_scaffold-nestjs
sonar.organization=general-organization

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/*.e2e-spec.ts,**/test/**,src/main.ts

sonar.javascript.lcov.reportPaths=coverage/e2e/lcov.info
sonar.qualitygate.wait=true