sonar.projectKey=Agustin-Perezz_scaffold-nestjs
sonar.organization=general-organization

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/*.e2e-spec.ts,**/test/**,src/main.ts,src/app.module.ts,src/books.module.ts,src/infrastructure/database/database.module.ts

sonar.javascript.lcov.reportPaths=coverage/unit/lcov.info,coverage/e2e/lcov.info
sonar.qualitygate.wait=true